# Generated by Django 3.2.19 on 2023-06-22 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banque', '0003_compte_prelevement_virement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compte',
            old_name='numero',
            new_name='nom',
        ),
    ]
