# Generated by Django 3.2.19 on 2023-06-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banque', '0004_rename_numero_compte_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='en_attente',
            field=models.BooleanField(default=False),
        ),
    ]
